/*
 * @Author: your name
 * @Date: 2020-11-17 11:08:44
 * @LastEditTime: 2020-12-08 15:41:27
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \src\InterfaceVariable\variable.ts
 */
/**
 * @desc 定义全局变量
 */
import { Page } from './interface'


// 限制输入框最大输入个数
export const LimitInputlength = 30;
export const textarealength = 200

export const page: Page = {
  currentPage: 1, //当前页数
  pageSize: 15, //每页多少条
  totalResult: 200, //总数
}
export const pagesize = [10, 20, 100, 200]
export const layouts: Array<string> = [
  "PrevJump",
  "PrevPage",
  "Jump",
  "PageCount",
  "NextPage",
  "NextJump",
  "Sizes",
  "Total",
]
export const list = [
  {
    key: "1",
    path: "/home",
    name: "home",
    redirect: null,
    component: "Index/Home.vue",
    hidden: false,
    meta: {
      key: "1",
      title: "系统首页",
      icon: "",
      keepAlive: false,
      permission: null,
    },
    children: null,
  },
  {
    key: "3",
    path: "/file",
    name: "file",
    redirect: null,
    component: "Index/Home.vue",
    hidden: false,
    meta: {
      key: "3",
      title: "数据中心",
      icon: ";",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "13",
        path: "/avData",
        name: "avData",
        redirect: null,
        component: "DataM/AvData.vue",
        hidden: false,
        meta: {
          key: "13",
          title: "视音频数据",
          icon: "icondata_video",
          keepAlive: false,
          permission: [
            "lawarchives:avDate:foreBtn",
            "lawarchives:avDate:twoTab",
            "lawarchives:avDate:download",
            "lawarchives:avDate:twoDel",
            "lawarchives:avDate:threeBtn",
            "lawarchives:avDate:deletes",
            "lawarchives:avDate:downloads",
            "lawarchives:avDate:oneBtn",
            "lawarchives:avDate:look",
            "lawarchives:avDate:fourTab",
            "lawarchives:avDate:twoAdd",
          ],
        },
        children: null,
      },
      {
        key: "14",
        path: "/Simpleprogram",
        name: "Simpleprogram",
        redirect: null,
        component: "DataM/Simpleprogram.vue",
        hidden: false,
        meta: {
          key: "14",
          title: "简易程序",
          icon: "icondata_program",
          keepAlive: false,
          permission: [
            "lawarchives:lllegalData:addRelated",
            "lawarchives:lllegalData:download",
            "lawarchives:lllegalData:delRelated",
            "lawarchives:lllegalData:file",
            "lawarchives:lllegalData:look",
          ],
        },
        children: null,
      },
      {
        key: "141",
        path: "/Coercivemeasures",
        name: "Coercivemeasures",
        redirect: null,
        component: "DataM/Coercivemeasures.vue",
        hidden: false,
        meta: {
          key: "141",
          title: "强制措施",
          icon: "icondata_measure",
          keepAlive: false,
          permission: [
            "lawarchives:lllegalData:addRelated",
            "lawarchives:lllegalData:download",
            "lawarchives:lllegalData:delRelated",
            "lawarchives:lllegalData:file",
            "lawarchives:lllegalData:look",
          ],
        },
        children: null,
      },
      

      {
        key: "9",
        path: "/videostatistics",
        name: "videostatistics",
        redirect: null,
        component: "StatisticalAnalysis/VideoStatistics.vue",
        hidden: false,
        meta: {
          key: "9",
          title: "摄录统计",
          icon: "icondata_vidg",
          keepAlive: false,
          permission: ["recording:export"]
        },
        children: null
      },
      {
        key: "10",
        path: "/lawcase",
        name: "lawcase",
        redirect: null,
        component: "StatisticalAnalysis/Lawcase.vue",
        hidden: false,
        meta: {
          key: "10",
          title: "关联统计",
          icon: "icondata_relation",
          keepAlive: false,
          permission: ["lawcase:export"]
        },
        children: null
      },
      {
        key: "11",
        path: "/label",
        name: "label",
        redirect: null,
        component: "StatisticalAnalysis/Label.vue",
        hidden: false,
        meta: {
          key: "11",
          title: "考评统计",
          icon: "iconplatform_upload",
          keepAlive: false,
          permission: ["label:export"]
        },
        children: null
      },
    ],
  },
  {
    key: "4",
    path: "/supervise",
    name: "supervise",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "4",
      title: "考评中心",
      icon: "&#xe6b2;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "17",
        path: "/evalRecord",
        name: "evalRecord",
        redirect: null,
        component: "Supervision/EvalRecord.vue",
        hidden: false,
        meta: {
          key: "17",
          title: "考评结果",
          icon: "iconsupervise_evaluate",
          keepAlive: false,
          permission: [
            "fileEvaluate:evaluationRecord:download",
            "evaluationRecord:twoTab",
            "fileEvaluate:evaluationRecord:look",
          ],
        },
        children: null,
      },
      {
        key: "18",
        path: "/evalDaily",
        name: "evalDaily",
        redirect: null,
        component: "Supervision/EvalDaily.vue",
        hidden: false,
        meta: {
          key: "18",
          title: "日常考评",
          icon: "iconsupervise_daily",
          keepAlive: false,
          permission: [
            "fileEvaluate:evaluationDaily:saveEva",
            "evaluationDaily:twoTab",
            "fileEvaluate:evaluationDaily:download",
            "fileEvaluate:evaluationDaily:look",
          ],
        },
        children: null,
      },
      {
        key: "19",
        path: "/evalRandom",
        name: "evalRandom",
        redirect: null,
        component: "Supervision/EvalRandom.vue",
        hidden: false,
        meta: {
          key: "19",
          title: "随机抽查",
          icon: "iconsupervise_check",
          keepAlive: false,
          permission: [
            "fileEvaluate:evaluationRandom:look",
            "fileEvaluate:evaluationRandom:download",
            "evaluationRandom:twoTab",
            "fileEvaluate:evaluationRandom:saveEva",
          ],
        },
        children: null,
      },
      {
        key: "20",
        path: "/evalSet",
        name: "evalSet",
        redirect: null,
        component: "Supervision/EvalSet.vue",
        hidden: false,
        meta: {
          key: "20",
          title: "考评设置",
          icon: "iconsupervise_statistics",
          keepAlive: false,
          permission: ["fileEvaluate:evSet:save", "fileEvaluate:evSet:add"],
        },
        children: null,
      },
    ],
  },
  {
    key: "5",
    path: "/mdm",
    name: "mdm",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "5",
      title: "资产中心",
      icon: "&#xe66b;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "21",
        path: "/matche",
        name: "matche",
        redirect: null,
        component: "Device/Matche.vue",
        hidden: false,
        meta: {
          key: "21",
          title: "执法仪",
          icon: "iconassets_law",
          keepAlive: false,
          permission: [
            "device:matche:export",
            "device:matche:list",
            "device:matche:save",
            "device:matcherepairs:acive",
            "device:matche:import",
            "device:matche:delete",
            "device:matcheRepair:list",
            "device:matche:update",
            "device:matche:repair",
            "device:matche:active",
          ],
        },
        children: null,
      },
      {
        key: "210",
        path: "/matcheRepair",
        name: "matcheRepair",
        redirect: null,
        component: "Device/Repairrecord.vue",
        hidden: false,
        meta: {
          key: "210",
          title: "执法仪报修",
          icon: "iconassets_guarantee",
          keepAlive: false,
          permission: [
            "device:matche:export",
            "device:matche:list",
            "device:matche:save",
            "device:matcherepairs:acive",
            "device:matche:import",
            "device:matche:delete",
            "device:matcheRepair:list",
            "device:matche:update",
            "device:matche:repair",
            "device:matche:active",
          ],
        },
        children: null,
      },
      {
        key: "22",
        path: "/stations",
        name: "stations",
        redirect: null,
        component: "Device/Stations.vue",
        hidden: false,
        meta: {
          key: "22",
          title: "采集设备",
          icon: "iconassets_equipment",
          keepAlive: false,
          permission: [
            "device:stations:active",
            "device:stations:disable",
            "device:stations:list",
            "device:stations:sync",
            "device:stations:delete",
            "device:stations:restart",
            "device:stations:upgrade",
            "device:stations:export",
            "device:stations:shutdown",
          ],
        },
        children: null,
      },
      {
        key: "23",
        path: "/storage",
        name: "storage",
        redirect: null,
        component: "Device/Storage.vue",
        hidden: false,
        meta: {
          key: "23",
          title: "存储设备",
          icon: "iconassets_store",
          keepAlive: false,
          permission: [
            "device:storage:delete",
            "device:storage:list",
            "device:storageFtp:delete",
            "device:storage:save",
            "device:storageFtp:save",
            "device:storage:update",
            "device:storage:ftp",
            "device:storageFtp:update",
          ],
        },
        children: null,
      },
      {
        key: "24",
        path: "/platform",
        name: "platform",
        redirect: null,
        component: "Device/Platform.vue",
        hidden: false,
        meta: {
          key: "24",
          title: "子平台",
          icon: "iconziping",
          keepAlive: false,
          permission: ["device:platform:list", "device:platform:delete"],
        },
        children: null,
      },
      {
        key: "12",
        path: "/assets",
        name: "assets",
        redirect: null,
        component: "StatisticalAnalysis/Assets.vue",
        hidden: false,
        meta: {
          key: "12",
          title: "资产统计",
          icon: "iconuser_privileges",
          keepAlive: false,
          permission: ["assets:export"]
        },
        children: null
      }
    ],
  },
  {
    key: "6",
    path: "/devops",
    name: "devops",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "6",
      title: "配置中心",
      icon: "&#xe6b3;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "15",
        path: "/lawarchives",
        name: "lawarchives",
        redirect: null,
        component: "DataM/Lawarchives.vue",
        hidden: false,
        meta: {
          key: "15",
          title: "关联规则",
          icon: "icondata_relation",
          keepAlive: false,
          permission: ["lawarchives:config:save"],
        },
        children: null,
      },
      {
        key: "16",
        path: "/recording",
        name: "recording",
        redirect: null,
        component: "DataM/Recording.vue",
        hidden: false,
        meta: {
          key: "16",
          title: "存储规则",
          icon: "icondeploy_save",
          keepAlive: false,
          permission: [
            "lawarchives:storageCategory:save",
            "lawarchives:storageCategory:update",
            "lawarchives:storageCategory:delete",
          ],
        },
        children: null,
      },
      {
        key: "35",
        path: "/Dictionary",
        name: "Dictionary",
        redirect: null,
        component: "systemM/Dictionary.vue",
        hidden: false,
        meta: {
          key: "35",
          title: "数据字典",
          icon: "icondeploy_dictionary",
          keepAlive: false,
          permission: [
            "base:dict:list",
            "base:dict:delete",
            "base:dict:save",
            "base:dict:update",
          ],
        },
        children: null,
      },
      {
        key: "37",
        path: "/HighConfig",
        name: "HighConfig",
        redirect: null,
        component: "systemM/HighConfig.vue",
        hidden: false,
        meta: {
          key: "37",
          title: "高级配置",
          icon: "icondeploy_configure",
          keepAlive: false,
          permission: ["system:highConfig:list", "system:highConfig:update"],
        },
        children: null,
      },
      
    ],
  },
  {
    key: "7",
    path: "/Usercore",
    name: "Usercore",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "7",
      title: "用户中心",
      icon: "&#xe66a;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "29",
        path: "/dept",
        name: "dept",
        redirect: null,
        component: "Organization/Dept.vue",
        hidden: false,
        meta: {
          key: "29",
          title: "部门管理",
          icon: "iconuser_branch",
          keepAlive: false,
          permission: [
            "base:dept:list",
            "base:dept:import",
            "base:dept:delete",
            "base:dept:save",
            "base:dept:export",
            "base:dept:update",
            "base:dept:savelow",
          ],
        },
        children: null,
      },
      {
        key: "30",
        path: "/user",
        name: "user",
        redirect: null,
        component: "Organization/User.vue",
        hidden: false,
        meta: {
          key: "30",
          title: "用户管理",
          icon: "iconuser_user",
          keepAlive: false,
          permission: [
            "base:user:update",
            "base:user:export",
            "base:user:list",
            "base:user:accessdd",
            "base:user:delete",
            "base:user:save",
            "base:user:import",
            "base:user:reset",
            "base:user:access",
            "base:user:4glist",
          ],
        },
        children: null,
      },
      {
        key: "31",
        path: "/role",
        name: "role",
        redirect: null,
        component: "Organization/Role.vue",
        hidden: false,
        meta: {
          key: "31",
          title: "角色管理",
          icon: "iconuser_privileges",
          keepAlive: false,
          permission: [
            "role:update",
            "role:list",
            "role:delete",
            "role:refright",
            "role:save",
            "role:right",
          ],
        },
        children: null,
      },
      {
        key: "33",
        path: "/right",
        name: "right",
        redirect: null,
        component: "Organization/Right.vue",
        hidden: false,
        meta: {
          key: "33",
          title: "权限管理",
          icon: "iconuser_privileges",
          keepAlive: false,
          permission: [
            "menu:right:list",
            "right:list",
            "right:refmenu",
            "right:update",
            "right:delete",
            "right:save",
            "right:update,right:refmenu"
          ],
        },
        children: null,
      },
      {
        key: "311",
        path: "/Menu",
        name: "Menu",
        redirect: null,
        component: "Organization/Menu.vue",
        hidden: false,
        meta: {
          key: "311",
          title: "菜单管理",
          icon: "iconuser_menu",
          keepAlive: false,
          permission: [
            "menu:save",
            "menu:update",
            "menu:delete",
            
          ],
        },
        children: null,
      }
    ],
  },
  {
    key: "8",
    path: "/PlatformM",
    name: "PlatformM",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "8",
      title: "平台管理",
      icon: "&#xe66c;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "34",
        path: "/Announcement",
        name: "Announcement",
        redirect: null,
        component: "systemM/Announcement.vue",
        hidden: false,
        meta: {
          key: "34",
          title: "公告管理",
          icon: "iconplatform_notice",
          keepAlive: false,
          permission: [
            "system:notice:update",
            "system:notice:export",
            "system:notice:delete",
            "system:notice:list",
            "system:notice:save",
          ],
        },
        children: null,
      },
      {
        key: "28",
        path: "/operationLog",
        name: "operationLog",
        redirect: null,
        component: "DevOps/OperationLog.vue",
        hidden: false,
        meta: {
          key: "28",
          title: "日志管理",
          icon: "iconplatform_journal",
          keepAlive: false,
          permission: ["base:log:list", "base:log:export"],
        },
        children: null,
      },
      {
        key: "38",
        path: "/Authorization",
        name: "Authorization",
        redirect: null,
        component: "systemM/Authorization.vue",
        hidden: false,
        meta: {
          key: "38",
          title: "授权信息",
          icon: "iconplatform_empower",
          keepAlive: false,
          permission: null,
        },
        children: null,
      },
      {
        key: "36",
        path: "/Setting",
        name: "Setting",
        redirect: null,
        component: "systemM/Setting.vue",
        hidden: false,
        meta: {
          key: "36",
          title: "平台设置",
          icon: "iconsetting",
          keepAlive: false,
          permission: ["system:setting:list", "system:setting:save"],
        },
        children: null,
      },
      // {
      //   key: "25",
      //   path: "/oMonitor",
      //   name: "oMonitor",
      //   redirect: null,
      //   component: "DevOps/OMonitor.vue",
      //   hidden: false,
      //   meta: {
      //     key: "25",
      //     title: "运行监控",
      //     icon: "&#xe6be;",
      //     keepAlive: false,
      //     permission: [
      //       "edvice:oMonitor:zptlist",
      //       "edvice:oMonitor:cjzlist",
      //       "edvice:oMonitor:fwqlist",
      //     ],
      //   },
      //   children: null,
      // },
      {
        key: "26",
        path: "/accessAuth",
        name: "accessAuth",
        redirect: null,
        component: "DevOps/AccessAuth.vue",
        hidden: false,
        meta: {
          key: "26",
          title: "密钥管理",
          icon: "iconkey",
          keepAlive: false,
          permission: [
            "system:authorization:cjz",
            "system:authorization:update",
            "system:authorization:list",
            "system:authorization:zpt",
            "system:authorization:delete",
          ],
        },
        children: null,
      },
      {
        key: "27",
        path: "/upgrade",
        name: "upgrade",
        redirect: null,
        component: "DevOps/Upgrade.vue",
        hidden: false,
        meta: {
          key: "27",
          title: "升级包管理",
          icon: "iconassets_upgrade",
          keepAlive: false,
          permission: [
            "system:upgrade:list",
            "system:upgrade:delete",
            "system:upgrade:save",
            "system:upgrade:update",
          ],
        },
        children: null,
      },
    ],
  },
];
