/*
 * @Author: your name
 * @Date: 2020-11-17 11:08:44
 * @LastEditTime: 2021-02-23 13:48:38
 * @LastEditors: yqn
 * @Description: In User Settings Edit
 * @FilePath: \src\InterfaceVariable\variable.ts
 */
/**
 * @desc 定义全局变量
 */
import { Page } from "./interface";

// 限制输入框最大输入个数
export const LimitInputlength = 30;
export const textarealength = 200;
export const sizeInputlength = 30
export const page: Page = {
  currentPage: 1, //当前页数
  pageSize: 15, //每页多少条
  totalResult: 200, //总数
};
export const pagesize = [10, 20, 100, 200];
export const layouts: Array<string> = [
  "PrevJump", 

  
  "PrevPage",
  "Jump",
  "PageCount",
  "NextPage",
  "NextJump",
  "Sizes",
  "Total",
];
export const list = [
  {
    key: "1",
    path: "/home",
    name: "home",
    redirect: null,
    component: "Index/Home.vue",
    hidden: false,
    meta: {
      key: "1",
      title: "系统首页",
      icon: "",
      keepAlive: false,
      permission: null,
    },
    children: null,
  },
  {
    key: "3",
    path: "/file",
    name: "file",
    redirect: null,
    component: "Index/Home.vue",
    hidden: false,
    meta: {
      key: "3",
      title: "数据中心",
      icon: ";",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "13",
        path: "/avData",
        name: "avData",
        redirect: null,
        component: "DataM/AvData.vue",
        hidden: false,
        meta: {
          key: "13",
          title: "视音频数据",
          icon: "icondata_video",
          keepAlive: false,
          permission: [
            "lawarchives:avDate:foreBtn",
            "lawarchives:avDate:twoTab",
            "lawarchives:avDate:download",
            "lawarchives:avDate:twoDel",
            "lawarchives:avDate:threeBtn",
            "lawarchives:avDate:deletes",
            "lawarchives:avDate:downloads",
            "lawarchives:avDate:oneBtn",
            "lawarchives:avDate:look",
            "lawarchives:avDate:fourTab",
            "lawarchives:avDate:twoAdd",
          ],
        },
        children: null,
      },
    ],
  },
  {
    key: "5",
    path: "/mdm",
    name: "mdm",
    redirect: null,
    component: "",
    hidden: false,
    title: "设备中心",
    icon: "&#xe66b;",
    keepAlive: false,
    permission: null,
    children: [
      {
        key: "21",
        path: "/matche",
        name: "matche",
        redirect: null,
        component: "Device/Matche.vue",
        hidden: false,
        meta: {
          key: "21",
          title: "执法仪",
          icon: "iconassets_law",
          keepAlive: false,
          permission: [
            "device:matche:export",
            "device:matche:list",
            "device:matche:save",
            "device:matcherepairs:acive",
            "device:matche:import",
            "device:matche:delete",
            "device:matcheRepair:list",
            "device:matche:update",
            "device:matche:repair",
            "device:matche:active",
          ],
        },
        children: null,
      },
      {
        key: "27",
        path: "/upgrade",
        name: "upgrade",
        redirect: null,
        component: "DevOps/Upgrade.vue",
        hidden: false,
        meta: {
          key: "27",
          title: "执法仪升级",
          icon: "iconassets_upgrade",
          keepAlive: false,
          permission: [
            "system:upgrade:list",
            "system:upgrade:delete",
            "system:upgrade:save",
            "system:upgrade:update",
          ],
        },
        children: null,
      },
      {
        key: "99",
        path: "/upgrade",
        name: "upgrade",
        redirect: null,
        component: "DevOps/Upgrade.vue",
        hidden: false,
        meta: {
          key: "27",
          title: "采集站升级",
          icon: "iconassets_upgrade",
          keepAlive: false,
          permission: [
            "system:upgrade:list",
            "system:upgrade:delete",
            "system:upgrade:save",
            "system:upgrade:update",
          ],
        },
        children: null,
      },
    ],
  },
  {
    key: "7",
    path: "/Usercore",
    name: "Usercore",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "7",
      title: "用户中心",
      icon: "&#xe66a;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "30",
        path: "/user",
        name: "user",
        redirect: null,
        component: "Organization/User.vue",
        hidden: false,
        meta: {
          key: "30",
          title: "用户管理",
          icon: "iconuser_user",
          keepAlive: false,
          permission: [
            "base:user:update",
            "base:user:export",
            "base:user:list",
            "base:user:accessdd",
            "base:user:delete",
            "base:user:save",
            "base:user:import",
            "base:user:reset",
            "base:user:access",
            "base:user:4glist",
          ],
        },
        children: null,
      },
      {
        key: "31",
        path: "/role",
        name: "role",
        redirect: null,
        component: "Organization/Role.vue",
        hidden: false,
        meta: {
          key: "31",
          title: "角色管理",
          icon: "iconuser_privileges",
          keepAlive: false,
          permission: [
            "role:update",
            "role:list",
            "role:delete",
            "role:refright",
            "role:save",
            "role:right",
          ],
        },
        children: null,
      },
      {
        key: "33",
        path: "/right",
        name: "right",
        redirect: null,
        component: "Organization/Right.vue",
        hidden: false,
        meta: {
          key: "33",
          title: "权限管理",
          icon: "iconuser_privileges",
          keepAlive: false,
          permission: [
            "menu:right:list",
            "right:list",
            "right:refmenu",
            "right:update",
            "right:delete",
            "right:save",
            "right:update,right:refmenu",
          ],
        },
        children: null,
      },
      {
        key: "311",
        path: "/Menu",
        name: "Menu",
        redirect: null,
        component: "Organization/Menu.vue",
        hidden: false,
        meta: {
          key: "311",
          title: "菜单管理",
          icon: "iconuser_menu",
          keepAlive: false,
          permission: ["menu:save", "menu:update", "menu:delete"],
        },
        children: null,
      },
    ],
  },
  {
    key: "6",
    path: "/devops",
    name: "devops",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "6",
      title: "系统管理",
      icon: "&#xe6b3;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "35",
        path: "/Dictionary",
        name: "Dictionary",
        redirect: null,
        component: "systemM/Dictionary.vue",
        hidden: false,
        meta: {
          key: "35",
          title: "数据字典",
          icon: "icondeploy_dictionary",
          keepAlive: false,
          permission: [
            "base:dict:list",
            "base:dict:delete",
            "base:dict:save",
            "base:dict:update",
          ],
        },
        children: null,
      },
      {
        key: "28",
        path: "/operationLog",
        name: "operationLog",
        redirect: null,
        component: "DevOps/OperationLog.vue",
        hidden: false,
        meta: {
          key: "28",
          title: "日志管理",
          icon: "iconplatform_journal",
          keepAlive: false,
          permission: ["base:log:list", "base:log:export"],
        },
        children: null,
      },
      {
        key: "37",
        path: "/HighConfig",
        name: "HighConfig",
        redirect: null,
        component: "systemM/HighConfig.vue",
        hidden: false,
        meta: {
          key: "37",
          title: "高级配置",
          icon: "icondeploy_configure",
          keepAlive: false,
          permission: ["system:highConfig:list", "system:highConfig:update"],
        },
        children: null,
      },
      {
        key: "37",
        path: "/Systemsettings",
        name: "systemsettings",
        redirect: null,
        component: "",
        hidden: false,
        meta: {
          key: "37",
          title: "系统设置",
          icon: "icondeploy_configure",
          keepAlive: false,
          permission: [],
        },
        children: [
          {
            key: "38",
            path: "/Authorization",
            name: "Authorization",
            redirect: null,
            component: "systemM/Authorization.vue",
            hidden: false,
            meta: {
              key: "38",
              title: "[级联]执法仪",
              icon: "iconplatform_empower",
              keepAlive: false,
              permission: null,
            },
            children: null,
          },
          {
            key: "36",
            path: "/Setting",
            name: "Setting",
            redirect: null,
            component: "systemM/Setting.vue",
            hidden: false,
            meta: {
              key: "36",
              title: "[级联]用户管理",
              icon: "iconsetting",
              keepAlive: false,
              permission: ["system:setting:list", "system:setting:save"],
            },
            children: null,
          },
        ],
      },
    ],
  },
  {
    key: "8",
    path: "/PlatformM",
    name: "PlatformM",
    redirect: null,
    component: "",
    hidden: false,
    meta: {
      key: "8",
      title: "升级服务",
      icon: "&#xe66c;",
      keepAlive: false,
      permission: null,
    },
    children: [
      {
        key: "34",
        path: "/Announcement",
        name: "Announcement",
        redirect: null,
        component: "systemM/Announcement.vue",
        hidden: false,
        meta: {
          key: "34",
          title: "软件升级中",
          icon: "iconplatform_notice",
          keepAlive: false,
          permission: [
            "system:notice:update",
            "system:notice:export",
            "system:notice:delete",
            "system:notice:list",
            "system:notice:save",
          ],
        },
        children: null,
      },

      {
        key: "38",
        path: "/Authorization",
        name: "Authorization",
        redirect: null,
        component: "systemM/Authorization.vue",
        hidden: false,
        meta: {
          key: "38",
          title: "升级失败",
          icon: "iconplatform_empower",
          keepAlive: false,
          permission: null,
        },
        children: null,
      },
      {
        key: "36",
        path: "/Setting",
        name: "Setting",
        redirect: null,
        component: "systemM/Setting.vue",
        hidden: false,
        meta: {
          key: "36",
          title: "升级成功",
          icon: "iconsetting",
          keepAlive: false,
          permission: ["system:setting:list", "system:setting:save"],
        },
        children: null,
      },
    ],
  },
];
